In [5]:
import numpy as np 

arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [12]:
myarr = np.array([[1,2,3] ,[4,5,6], [7,8,9]])
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.size(myarr)

9

In [14]:
np.shape(myarr)

(3, 3)

In [15]:
myarr.ndim

2

In [16]:
myarr.dtype


dtype('int64')

In [17]:
myarr.astype("float64")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
myarr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])