In [1]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
flat[3]

np.int64(4)

In [9]:
flat[0]

np.int64(1)

In [10]:
flat[3:6]

array([4, 5, 6])

In [11]:
flat[0:4]

array([1, 2, 3, 4])

In [12]:
flat[7]

np.int64(8)

In [13]:
#Slicing of array
b = flat[0:5]

In [14]:
b

array([1, 2, 3, 4, 5])

In [15]:
b[2] = 143

In [16]:
b

array([  1,   2, 143,   4,   5])

In [17]:
flat

array([  1,   2, 143,   4,   5,   6,   7,   8,   9])

In [18]:
#if you only want to copy and dont want to make changes in original array then directly use .copy function
b = flat[0:5].copy()
b

array([  1,   2, 143,   4,   5])

In [19]:
b[2] = 1432
b

array([   1,    2, 1432,    4,    5])

In [20]:
flat

array([  1,   2, 143,   4,   5,   6,   7,   8,   9])

In [22]:
#Fancy indexing
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
arr[[2,4,6]]

array([3, 5, 7])

In [27]:
arr[arr>5]

array([6, 7])

In [29]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9]])
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
myarr.size

9

In [32]:
myarr.shape

(3, 3)

In [34]:
myarr = np.array([1.1,1.2,1.3], dtype = "int")
myarr

array([1, 1, 1])

In [42]:
arr = np.array([1,2,3,4,5,6,7,8])
arr
arr[1::2]

array([2, 4, 6, 8])

In [50]:
myarr = np.array([1,2,3,4,5,6,7,8,9])
myarr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
reshaped = myarr.reshape([3,3])
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1 = np.array([2,98,90,56,78,1,3])
arr1
arr1[arr1>50]

array([98, 90, 56, 78])

In [72]:
import numpy as np

arr2 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
np.sum(arr2,axis=0)

array([12, 15, 18])

In [69]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [70]:
arr2 = np.sum(arr,axis=1)
arr2

array([ 6, 15, 24])

In [73]:
print(arr2[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [75]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
  # Output: (2, 2, 3) 

In [76]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3D[:, 0 ,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [82]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [90]:
arr4 = np.array([1,2,3,4,5,6,7,8])
result = arr4 + 10
result

array([11, 12, 13, 14, 15, 16, 17, 18])

In [87]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [91]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [92]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

mean = data.mean(axis= 0)
std = data.std(axis = 0)

normalized = (data - mean) / std

normalized

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])

In [98]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [104]:
np.random.randint(1,101, size = 15) #creating array of 15 size by taking random numbers in between 1 to 100

array([89, 62, 37, 59, 95, 27,  9, 29, 74, 60, 13,  1,  4, 12, 81],
      dtype=int32)

In [109]:
marr = np.array([1,2,3,4,5,6,7,8,9])
marr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.min(marr)

np.int64(1)

In [116]:
np.max(marr)


np.int64(9)

In [118]:
np.mean(marr)

np.float64(5.0)

In [119]:
#Replace all odd numbers of an array with -1
marr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
marr[::2]

array([1, 3, 5, 7, 9])

In [133]:
marr[::2] = -1
marr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [142]:
#1st row and last column of array
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
array1[0:1, 2:3]


array([[3]])

In [140]:
np.diag(array1)

array([1, 5, 9])

In [146]:
array1 = np.array([1,2,3,4,5,6,7,8])
array1
array2 = np.array([1,2,3,4,5,6,7,8])
array2
result = array1 * array2
result





array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [5]:
import pandas as np
arr9 = np.array([1,2,3,4,5,6,7,8,9])
print(arr9)

mean = arr9.mean()
std = arr9.std()

normalized = (arr9 - mean )/std
normalized

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
Length: 9, dtype: Int64


<FloatingArray>
[-1.4605934866804429, -1.0954451150103321, -0.7302967433402214,
 -0.3651483716701107,                 0.0,  0.3651483716701107,
  0.7302967433402214,  1.0954451150103321,  1.4605934866804429]
Length: 9, dtype: Float64

In [6]:
import numpy as np

data = np.random.randn(1000, 5)
z = (data - data.mean(axis=0)) / data.std(axis=0)

# Flatten and find top 3
flat = z.flatten()
top3_idx = flat.argsort()[-3:][::-1]
top3_values = flat[top3_idx]
top3_positions = [np.unravel_index(i, z.shape) for i in top3_idx]

print("Top 3 Values:", top3_values)
print("Positions:", top3_positions)


Top 3 Values: [3.24220274 3.06899814 3.06772004]
Positions: [(np.int64(432), np.int64(1)), (np.int64(773), np.int64(3)), (np.int64(344), np.int64(1))]
